function straightLine = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STRAIGHTLINE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a cell array.
%
%  STRAIGHTLINE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  straightLine = importfile("C:\Users\Krithik\Documents\GitHub\P4P-Project-102\straightLine.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Aug-2022 19:25:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "x", "y", "z"];
opts.SelectedVariableNames = ["x", "y", "z"];
opts.VariableTypes = ["string", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "x", "y", "z"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "x", "y", "z"], "EmptyFieldRule", "auto");

% Import the data
straightLine = readtable(filename, opts);

%% Convert to output type
straightLine = table2cell(straightLine);
numIdx = cellfun(@(x) ~isnan(str2double(x)), straightLine);
straightLine(numIdx) = cellfun(@(x) {str2double(x)}, straightLine(numIdx));
end